#!/bin/bash

input_file="raw_data/satelite_temperature_data.csv"
humidity_output="analyzed_data/humidity_data_Kenya.csv"
number_output="results.txt"

grep "Kenya" "$input_file" | sort -t, -k4 -nr > "$humidity_output"
echo "Humidity data for Kenya has been saved to $humidity_output"

grep -o '[0-9]\+' "$input_file" | sort -nr | uniq | head -10 >> "$number_output"
echo "Top 10 unique numbers have been saved to $number_output"
